In [3]:
import pandas as pd
import numpy as np

In [5]:
a= np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [14]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3", "Row4", "Row5"])

0   1   2   3
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [23]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3", "Row4", "Row5"], columns=["Column1","Column2", "Column3", "Column4"])

In [25]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [26]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [30]:
df.tail(2)

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [31]:
type(df)

pandas.core.frame.DataFrame

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [36]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [45]:
df[['Column1','Column3']]

Column1  Column3
Row1        0        2
Row2        4        6
Row3        8       10
Row4       12       14
Row5       16       18

In [48]:
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [52]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [90]:
df.iloc[ : ,[0,3]]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19